// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgmNAVs6DnlMwENGDwMt-QEh-vIrmRAKM',
    appId: '1:254696780043:web:e90b2f778efc000855720e',
    messagingSenderId: '254696780043',
    projectId: 'komplech-events',
    authDomain: 'komplech-events.firebaseapp.com',
    storageBucket: 'komplech-events.firebasestorage.app',
    measurementId: 'G-E16X17BWB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCYBg-_PxNDsEVhFkrwc9utgQDTnRYouY',
    appId: '1:254696780043:android:bfcfffc70960494955720e',
    messagingSenderId: '254696780043',
    projectId: 'komplech-events',
    storageBucket: 'komplech-events.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFjEp6yePBwjzzRFLAOpoThFuUqr2sg_s',
    appId: '1:254696780043:ios:64de628157a46bc155720e',
    messagingSenderId: '254696780043',
    projectId: 'komplech-events',
    storageBucket: 'komplech-events.firebasestorage.app',
    iosBundleId: 'com.komplech.event',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFjEp6yePBwjzzRFLAOpoThFuUqr2sg_s',
    appId: '1:254696780043:ios:ef574ff42015cea955720e',
    messagingSenderId: '254696780043',
    projectId: 'komplech-events',
    storageBucket: 'komplech-events.firebasestorage.app',
    iosBundleId: 'com.komplech.event',
  );
}
